import typing

from .db_table import DBTable

if typing.TYPE_CHECKING:
    from typing import *
    from types import SimpleNamespace

__all__ = ['DBRowFactoryLike', 'DBRowLike', 'DBCopyLike', 'DBCursorLike', 'DBConnectionLike', 'DBPoolLike']

DBRowFactoryLike = 'Callable[[type[DBTable] | None], type]'
DBRowLike = DBTable | tuple | dict

class DBCopyLike(typing.Protocol):
    """Protocol for database copy"""
    def write_row(self, values: tuple): ...

class DBCursorLike(typing.Protocol):
    """Protocol for database cursor"""
    description: Sequence[tuple[str, ...]] | None
    def execute(self, sql: str, values: Optional[Sequence[Any]] = None) -> Iterator[SimpleNamespace | dict[str, Any] | DBTable]: ...
    def fetchone(self) -> Optional[tuple[Any]]: ...
    def fetchall(self) -> list[tuple[Any]]: ...
    def copy(self, sql: str) -> ContextManager[DBCopyLike]: ...

class DBConnectionLike(typing.Protocol):
    """Protocol for database connection"""
    def cursor(self, binary: bool, row_factory: type) -> ContextManager[DBCursorLike]: ...
    def execute(self, sql: str, values: Optional[Sequence[Any]] = None) -> Iterable[Any]: ...
    def executemany(self, sql: str, values: Sequence[Sequence[Any]]) -> Iterable[Any]: ...
    def executescript(self, sql: str) -> Iterable[Any]: ...
    def transaction(self) -> ContextManager[None]: ...
    def commit(self) -> None: ...

class DBPoolLike(typing.Protocol):
    """Protocol for database pool"""
    def getconn(self) -> DBConnectionLike: ...
    def putconn(self, conn: DBConnectionLike) -> None: ...
    def connection(self) -> ContextManager[DBConnectionLike]: ...
