import typing

from .db_table import DBTable

if typing.TYPE_CHECKING:
    from typing import *
    from types import SimpleNamespace

__all__ = ['DBRowFactoryLike', 'DBRowLike', 'DBCopyLike', 'DBCursorLike', 'DBConnectionLike', 'DBPoolLike']

DBRowFactoryLike = 'Callable[[type[DBTable] | None], type]'
DBRowLike = DBTable | tuple | dict

class DBCopyLike(typing.Protocol):
    """Protocol for database copy"""
    def write_row(self, values: tuple) -> Awaitable[None] | None: ...

class DBCursorLike(typing.Protocol):
    """Protocol for database cursor"""
    description: Sequence[tuple[str, ...]] | None
    def execute(self, sql: str, values: Optional[Sequence[Any]] = None) -> (
            Awaitable[Iterator[SimpleNamespace | dict[str, Any] | DBTable]] |
            Iterator[SimpleNamespace | dict[str, Any] | DBTable]): ...
    def executemany(self, sql: str, values: Sequence[Sequence[Any]]) -> Awaitable[Iterable[Any]] | Iterable[Any]: ...
    def executescript(self, sql: str, values: Sequence[Sequence[Any]]) -> Awaitable[Iterable[Any]] | Iterable[Any]: ...
    def fetchone(self) -> Awaitable[Optional[tuple[Any]]] | Optional[tuple[Any]]: ...
    def fetchall(self) -> Awaitable[list[tuple[Any]]] | list[tuple[Any]]: ...
    def copy(self, sql: str) -> AsyncContextManager[DBCopyLike] | ContextManager[DBCopyLike]: ...
    def commit(self) -> Awaitable[None] | None: ...

class DBConnectionLike(typing.Protocol):
    """Protocol for database connection"""
    def cursor(self, binary: bool=False, row_factory: type=None, **kwargs) -> (
            Awaitable[ContextManager[DBCursorLike]] |
            ContextManager[DBCursorLike]): ...
    def execute(self, sql: str, values: Optional[Sequence[Any]] = None) -> Awaitable[Iterable[Any]] | Iterable[Any]: ...
    def executemany(self, sql: str, values: Sequence[Sequence[Any]]) -> Awaitable[Iterable[Any]] | Iterable[Any]: ...
    def executescript(self, sql: str) -> Awaitable[Iterable[Any]] | Iterable[Any]: ...
    def transaction(self) -> AsyncContextManager[None] | ContextManager[None]: ...
    def commit(self) -> Awaitable[None] | None: ...

class DBPoolLike(typing.Protocol):
    """Protocol for database pool"""
    def connection(self, **kwargs) -> AsyncContextManager[DBConnectionLike] | ContextManager[DBConnectionLike]: ...
    def cursor(self, read_only: bool=False, _curr: DBCursorLike=None, **kwargs) -> AsyncGenerator[DBCursorLike] | Generator[DBCursorLike]: ...
    def close(self) -> Awaitable[None] | None: ...
